{{ range $_, $depl := .Values.blueGreen -}}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" $.Chart.Name $depl.colour }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Chart.Name }}
    colour: {{ $depl.colour }}
    version: {{ $depl.version }}
spec:
  replicas: 1
  # selector:
  #   matchlabels:
  #     app: {{ $.Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        colour: {{ $depl.colour }}
        version: {{ $depl.version }}
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: {{ $.Chart.Name }}
        image: {{ printf "%s:%s" $.Chart.Name  $depl.version }}
        # must be set to Never or IfNotPresent to work with local minikube
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 10Mi
          requests:
            cpu: 50m
            memory: 5Mi
        ports:
        - containerPort: {{ $.Values.port }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ $.Values.port }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ $.Values.port }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
{{ end }}