apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
      - name: {{ .Chart.Name }}
        image: {{ printf "%s:%s" .Chart.Name  .Chart.Version }}
        # imagePullPolicy must be Never or IfNotPresent to work in minikube
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 10Mi
          requests:
            cpu: 10m
            memory: 1Mi
        ports:
        - containerPort: {{ .Values.port }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.port }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10