apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # nginx.ingress.kubernetes.io/enable-cors: "true"
    # cors-allow-origin can only take one origin or is * per default
    # thats why we need CORS for origin in service
    # nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    # nginx.ingress.kubernetes.io/cors-allow-methods: "GET, OPTIONS"
    # nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  rules:
    - host: local.ecosia.org
      http:
        paths:
          - path: /(.+)
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: 8080