apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  currentLive: {{ .Values.hotDeployment }}
  currentVersion: {{ .Values.hotVersion }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
    targetPort: {{ .Values.port }}
    name: http
  selector:
    app: {{ .Chart.Name }}
    colour: {{ .Values.hotDeployment }}

  # sessionAffinity: None
